services:
  aidetector:
    image: "ghcr.io/eschouten/ai-detector:latest"
    restart: unless-stopped
    command: ["python3", "-m", "aidetector", "--live-preview"]
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864

    volumes:
      - ./example:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  web:
    image: "ghcr.io/eschouten/ai-detector-web:latest"
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "80:3000"
    volumes:
      - ./example:/data
