import Ajv from 'ajv';
import * as v from 'valibot';
import schema from '../../../config/config.schema.json' with { type: 'json' };
import type { AppConfig, Config, Configuration, DetectorConfig, TelegramConfig } from './schema.ts';

export class ConfigurationError extends Error {}

const text = v.pipe(v.string(), v.trim(), v.minLength(1));
export const detectorMeta = v.object({
	label: text,
	cameraId: v.optional(text),
	preset: v.optional(v.picklist(['calving', 'mounts', 'general']))
});
export const cameraConnectionMeta = v.object({
	address: v.pipe(
		text,
		v.check((value) => {
			try {
				const url = new URL(value);
				return (
					['http:', 'https:'].includes(url.protocol) &&
					!url.username &&
					!url.password &&
					!url.search &&
					!url.hash
				);
			} catch {
				return false;
			}
		}, 'Camera connection details must not contain login details or access tokens.')
	),
	profileToken: v.optional(text)
});
const timestamp = v.pipe(v.string(), v.isoTimestamp());
const cameraSetup = v.object({
	pictureVerifiedAt: v.optional(timestamp),
	archiveVerifiedAt: v.optional(timestamp),
	archiveSignature: v.optional(text),
	alerts: v.optional(v.literal('skipped')),
	completedAt: v.optional(timestamp),
	completionSignature: v.optional(text)
});
export const streamMeta = v.object({
	id: v.optional(text),
	label: v.optional(text),
	source: text,
	connection: v.optional(cameraConnectionMeta),
	setup: v.optional(cameraSetup)
});
const identity = v.pipe(v.string(), v.minLength(1));
export const telegramMeta = v.object({ label: text, token: identity, chat: identity });
const appSchema = v.object({
	streams: v.optional(v.array(streamMeta), []),
	telegrams: v.optional(v.array(telegramMeta), []),
	detectors: v.optional(v.array(detectorMeta), [])
});
export const detectorInput = v.object({
	original: v.optional(v.string()),
	detector: v.unknown(),
	meta: detectorMeta
});
export const streamInput = v.object({
	...v.pick(streamMeta, ['id', 'label', 'source']).entries,
	label: text,
	original: v.optional(v.string()),
	next: v.optional(v.string())
});
export const telegramInput = v.object({
	...telegramMeta.entries,
	token: text,
	chat: text,
	original: v.optional(v.string()),
	next: v.optional(v.string())
});
export const streamOrder = v.object({
	index0: v.pipe(v.number(), v.integer(), v.minValue(0)),
	index1: v.pipe(v.number(), v.integer(), v.minValue(0))
});

const cameraDetails = {
	label: text,
	source: text,
	checkId: v.optional(text),
	connection: v.optional(v.nullable(cameraConnectionMeta))
};
export const cameraInput = v.variant('preset', [
	v.object({
		...cameraDetails,
		id: v.optional(text),
		preset: v.picklist(['calving', 'mounts', 'general', 'view-only', 'keep']),
		copyFromCameraId: v.optional(v.never('Choose either a watched event or an existing camera.'))
	}),
	v.object({
		...cameraDetails,
		id: v.optional(v.never('Copy monitoring settings when adding a new camera.')),
		preset: v.literal('copy'),
		copyFromCameraId: text
	})
]);

export const alertsInput = v.object({
	...telegramInput.entries,
	cameraIds: v.array(text),
	received: v.boolean()
});

interface ConfigInput {
	$schema?: string | null;
	detectors: {
		detection: { source: string | string[]; [key: string]: unknown };
		exporters?: Record<string, Record<string, unknown> | Record<string, unknown>[] | null> | null;
		[key: string]: unknown;
	}[];
	[key: string]: unknown;
}

// The web app can save an empty setup or stop after deleting the last detector.
// All detector fields still use the canonical schema generated by Python.
const ajv = new Ajv({ strict: false, allErrors: true });
const validate = ajv.compile<ConfigInput>({
	...schema,
	properties: { ...schema.properties, detectors: { ...schema.properties.detectors, minItems: 0 } }
});

export function normalizeConfig(input: unknown): Config {
	if (!validate(input)) {
		throw new ConfigurationError(
			`Invalid detector configuration: ${ajv.errorsText(validate.errors)}`
		);
	}
	return {
		...input,
		detectors: input.detectors.map(({ detection, exporters, ...detector }) => {
			const sources = (Array.isArray(detection.source) ? detection.source : [detection.source]).map(
				(source) => source.trim()
			);
			if (new Set(sources).size !== sources.length)
				throw new ConfigurationError('A detector cannot use the same source more than once.');
			const normalized: NonNullable<DetectorConfig['exporters']> = {};
			for (const [name, values] of Object.entries(exporters ?? {})) {
				normalized[name] = values == null ? [] : Array.isArray(values) ? values : [values];
			}
			return {
				...detector,
				detection: {
					...detection,
					source: sources
				},
				exporters: normalized
			};
		})
	};
}

function uniqueLabel(label: string, used: Set<string>): string {
	let candidate = label;
	for (let suffix = 2; used.has(candidate); suffix++) candidate = `${label} (${suffix})`;
	used.add(candidate);
	return candidate;
}

export function sameTelegram(left: TelegramConfig, right: TelegramConfig): boolean {
	return left.token === right.token && left.chat === right.chat;
}

export function normalizeConfiguration(configInput: unknown, appInput: unknown): Configuration {
	const config = normalizeConfig(configInput);
	const app: AppConfig = v.parse(appSchema, appInput);
	const labels = new Set<string>();
	app.detectors = config.detectors.map((_, index) => ({
		...app.detectors[index],
		label: uniqueLabel(app.detectors[index]?.label ?? `Detector ${index + 1}`, labels)
	}));
	const streams = new Map(app.streams.map((stream) => [stream.source, stream]));
	for (const source of config.detectors.flatMap((detector) => detector.detection.source)) {
		if (!streams.has(source)) streams.set(source, { label: `Camera ${streams.size + 1}`, source });
	}
	app.streams = [...streams.values()];
	app.telegrams = app.telegrams.filter(
		(telegram, index, all) => all.findIndex((item) => sameTelegram(item, telegram)) === index
	);
	for (const telegram of config.detectors.flatMap(
		(detector) => detector.exporters?.telegram ?? []
	)) {
		if (!app.telegrams.some((item) => sameTelegram(item, telegram))) {
			app.telegrams.push({ label: telegram.chat, token: telegram.token, chat: telegram.chat });
		}
	}
	labels.clear();
	app.telegrams = app.telegrams.map((telegram) => ({
		...telegram,
		label: uniqueLabel(telegram.label, labels)
	}));
	return { config, app };
}

export { schema as configurationSchema };
