name: CI

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.ref_name }}-${{
    github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  publish:
    name: "publish image"
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/${{ github.repository_owner }}/ai-detector:latest,ghcr.io/${{ github.repository_owner }}/ai-detector:${{ github.ref_name }}
          cache-from: type=gha,scope=ai-detector
          cache-to: type=gha,mode=min,scope=ai-detector
          push: true

