name: CI

on:
  push:
    branches: [main, gha]
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.ref_name }}-${{
    github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  publish:
    name: "publish image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: free disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/eschouten/ai-detector:latest,ghcr.io/eschouten/ai-detector:${{ github.ref_name }}
          push: true

